### ISSUE TITLE
get calltrace when running not under git repository

### ISSUE THREAD

**Issue by dlan17** [stefanha/git-publish#103]
this is a calltrace when not running at git repository (no .git dir)
it would be great to check this early and yell at it

 $ git-publish
Traceback (most recent call last):
  File "/usr/bin/git-publish", line 914, in <module>
    sys.exit(main())
  File "/usr/bin/git-publish", line 632, in main
    if not check_profile_exists(options.profile_name):
  File "/usr/bin/git-publish", line 330, in check_profile_exists
    lines = git_config_with_profile('--get-regexp', '^gitpublishprofile\\.%s\\.' % profile_name)
  File "/usr/bin/git-publish", line 290, in git_config_with_profile
    gitpublish = os.path.abspath(os.path.join(git_get_toplevel_dir(), '.gitpublish'))
  File "/usr/bin/git-publish", line 149, in git_get_toplevel_dir
    GIT_TOPLEVEL = _git_check('rev-parse', '--show-toplevel')[0]
  File "/usr/bin/git-publish", line 72, in _git_check
    raise GitError('ERROR: %s\n%s' % (cmdstr, '\n'.join(stderr)))
__main__.GitError: ERROR: git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by stefanha** [comment]
@dlan17 What do you think about this?
https://github.com/stefanha/git-publish/commit/77a01d19fa484bb9f530d9e2d861f4e53d8bbc9d

**Comment by dlan17** [comment]
Great, this fix my issue and much clear for user to know the problem..

**Comment by dlan17** [comment]
btw, I've pushed this package into Gentoo's portage repository,
so any user of Gentoo will benefit from your work, thanks again

https://github.com/gentoo/gentoo/commit/300ca15b52e08471e02602f7422010f1e05d166a

**Comment by stefanha** [comment]
@dlan17 Thank you! I have pushed the fix.
