### ISSUE TITLE
Branch description overrides body of cover letter

### ISSUE THREAD

**Issue by gkurz** [stefanha/git-publish#105]
If an stgit branch has a description and then you git publish the changes on this branch, no matter what you put in the cover
during the editing phase, the body of the cover letter displays the stgit description instead.

$ stg branch --description="THIS TEXT SHOULD NOT END UP IN THE GIT PUBLISH COVER LETTER"
$ git publish -b ${base_branch} --subject-prefix RFC
Stopping so you can inspect the patch emails:
[ put a valid subject and description of the series ]
  cd /tmp/tmpppoyqbry
...
$ cd /tmp/tmpppoyqbry
$ cat 0000-cover-letter.patch 
From: Greg Kurz <groug@kaod.org>
Date: Wed, 24 Mar 2021 10:43:43 +0100
Subject: [RFC 0/8] virtio: Improve boot time of virtio-scsi-pci and virtio-blk-pci
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
MIME-Version: 1.0

THIS TEXT SHOULD NOT END UP IN THE GIT PUBLISH COVER LETTER

Greg Kurz (8):
  memory: Allow eventfd add/del without starting a transaction
  virtio: Introduce virtio_bus_set_host_notifiers()
  virtio: Add API to batch set host notifiers
  virtio-pci: Batch add/del ioeventfds in a single MR transaction
  virtio-blk: Fix rollback path in virtio_blk_data_plane_start()
  virtio-blk: Use virtio_bus_set_host_notifiers()
  virtio-scsi: Set host notifiers and callbacks separately
  virtio-scsi: Use virtio_bus_set_host_notifiers()

 hw/virtio/virtio-pci.h          |  1 +
 include/exec/memory.h           | 48 ++++++++++++++++------
 include/hw/virtio/virtio-bus.h  |  7 ++++
 hw/block/dataplane/virtio-blk.c | 26 +++++-------
 hw/scsi/virtio-scsi-dataplane.c | 68 ++++++++++++++++++--------------
 hw/virtio/virtio-bus.c          | 70 +++++++++++++++++++++++++++++++++
 hw/virtio/virtio-pci.c          | 53 +++++++++++++++++--------
 softmmu/memory.c                | 42 ++++++++++++--------
 8 files changed, 225 insertions(+), 90 deletions(-)

-- 
2.26.3

**Comment by gkurz** [comment]
If the stgit description is removed, everything works as expected.

$ stg branch --description=""
$ git publish -b ${base_branch} --subject-prefix RFC
Stopping so you can inspect the patch emails:
[ put a valid subject and description of the series ]
Stopping so you can inspect the patch emails:
  cd /tmp/tmpvct_6ybj
...
$ cd /tmp/tmpvct_6ybj
$ head 0000-cover-letter.patch 
From: Greg Kurz <groug@kaod.org>
Date: Wed, 24 Mar 2021 11:00:19 +0100
Subject: [RFC 0/8] virtio: Improve boot time of virtio-scsi-pci and virtio-blk-pci
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
MIME-Version: 1.0

Now that virtio-scsi-pci and virtio-blk-pci map 1 virtqueue per vCPU,
a serious slow down may be observed on setups with a big enough number
of vCPUs.

**Comment by stefanha** [comment]
On IRC we figured it must be because both stgit and git-publish store a '<branch>-staging' tag. They are interfering with each other. git-publish looks for the staging tag where it stores the work-in-progress cover letter saved by git-publish --edit. The tag suffix could be turned into a configuration setting so that you can set a unique name in ~/.gitconfig. Unfortunately I can't think of a way to do this automatically while remaining backwards compatible, so I guess it needs to be an explicit git-config(1) setting.

**Comment by stefanha** [comment]
Greg looked at the issue in more detail and found out it was git-format-patch(1) using the branch's description. It wasn't the -staging tag.
