### ISSUE TITLE
Release 1.8.2

### ISSUE THREAD

**Issue by samueltardieu** [stefanha/git-publish#119]
Hi.

Since version 1.8.1 has been released, a new option `--send-email-args` have been added which would be very handy in some cases. For example, we are limited by a university mail server in the rate of mails we can send. Being able to use `--send-email-args "--batch-size 1 --relogin-delay 10"` when sending a large patch series would be very handy.

Would it be possible to release version 1.8.2 of `git-publish`?

**Comment by stefanha** [comment]
@samueltardieu Sure, I will publish a release.
