### ISSUE TITLE
Request confirmation for pull-request if only an SSH URI is available

### ISSUE THREAD

**Issue by berrange** [stefanha/git-publish#35]
I sent my first pull request for QEMU with git-publish and the cover letter it wrote included an SSH URI scheme, because I didn't remember it would need a separate URI configured for pull vs push.

git-publish could usefully request confirmation before sending the pull request, if it finds only a SSH URI present, to prevent such mistakes.

**Comment by stefanha** [comment]
On Fri, Feb 16, 2018 at 9:20 AM, Daniel Berrange <notifications@github.com>
wrote:

> I sent my first pull request for QEMU with git-publish and the cover
> letter it wrote included an SSH URI scheme, because I didn't remember it
> would need a separate URI configured for pull vs push.
>
> git-publish could usefully request confirmation before sending the pull
> request, if it finds only a SSH URI present, to prevent such mistakes.
>
Thanks for the feature request, it sounds like a helpful check to add
before sending pull requests.

I hope to implement it soon along with a way to override the warning for
people who have a workflow that really involves sending SSH URIs in pull
request cover letters.

Stefan

**Comment by stefanha** [comment]
Implemented!
https://github.com/stefanha/git-publish/commit/9ee447ad2fca2ad0b759a11a566459bb7da71bfa
