### ISSUE TITLE
Provide a man page for git-publish

### ISSUE THREAD

**Issue by berrange** [stefanha/git-publish#36]
Command line tools are usually accompanied by man pages to describe their usage, but git-publish lacks one right now.

Much of what is in README.rst could be turned into POD syntax from which a man page could be created.

This would be particularly helpful for making 'git publish --help' work as that just runs 'man git-$COMMAND', so currently you get

$ git publish --help
No manual entry for git-publish

**Comment by berrange** [comment]
Also reported downstream at https://bugzilla.redhat.com/show_bug.cgi?id=1545853

**Comment by stefanha** [comment]
On Fri, Feb 16, 2018 at 9:22 AM, Daniel Berrange <notifications@github.com>
wrote:

> Also reported downstream at https://bugzilla.redhat.com/
> show_bug.cgi?id=1545853
>

Thanks, I will tackle this soon.

Stefan

**Comment by stefanha** [comment]
The man page has been merged!  I took your idea and converted README.rst to POD.  Luckily GitHub can also render README.pod files so there is no loss in functionality for the GitHub repository landing page.
