### ISSUE TITLE
's' command in inspect menu does not work as expected

### ISSUE THREAD

**Issue by Fabian-Gruenbichler** [stefanha/git-publish#39]
#32 added an 's' command in the inspect menu which allows selecting patches for sending. this is broken - the modified patches variable is used in the inspect menu, but not propagated back to line #734. instead of sending the subset of patches that were selected, all patches are sent. the check for modified patch files does not trigger, because the patch files are not removed.

I am not enough of a python person to know how to implement this correctly, but IMHO:
- the value of patches need to be propagated back from the inspect menu to the call site
- upon hitting "send all", all non-selected patch files should be removed from the tmpdir

ideally, the 's' command handling would re-initialize the tmpfile used for selection using all patches, not just the selected ones. this would allow selecting a subset, but then re-including a patch that was deselected without restarting the whole git-publish process.

**Comment by stefanha** [comment]
@Fabian-Gruenbichler Thanks for your bug report!  We'll get it fixed for the next git-publish release.

@famz Do you want to look at this?

**Comment by Fabian-Gruenbichler** [comment]
great!

FWIW, I did the quick workaround below locally, which together with manual removal of skipped patches from the tmpdir works for now, but obviously that is not a good permanent solution ;)

```
diff --git a/git-publish b/git-publish
index 695b8f1..2c61191 100755
--- a/git-publish
+++ b/git-publish
@@ -780,17 +780,8 @@ branch.%s.pushRemote is set appropriately?  (Override with --no-url-check)''' %
             invoke_hook('pre-publish-send-email', tmpdir)
 
             final_patches = sorted(glob.glob(os.path.join(tmpdir, '*')))
-            if final_patches != patches:
-                added = set(final_patches).difference(set(patches))
-                deleted = set(patches).difference(set(final_patches))
-                print("The list of files in %s changed and I don't know what to do" % tmpdir)
-                if added:
-                    print('Added files: %s' % ' '.join(added))
-                if deleted:
-                    print('Deleted files: %s' % ' '.join(deleted))
-                return 1
-
-            git_send_email(to, cc, patches, suppress_cc, options.in_reply_to)
+
+            git_send_email(to, cc, final_patches, suppress_cc, options.in_reply_to)
         except (GitError, GitSendEmailError, GitHookError, InspectEmailsError):
             return 1
         finally:
```

**Comment by famz** [comment]
I've sent the patch to Stefan offline:
```
From: Fam Zheng <famz@redhat.com>
Date: Thu, 1 Mar 2018 09:51:07 +0800
Subject: [PATCH] Fix 's' command

The modification to "patches" in inspect_menu is not propagated back to
the final git_send_email command. Add a return value to fix that.

Signed-off-by: Fam Zheng <famz@redhat.com>

diff --git a/git-publish b/git-publish
index ab9f6bf..4f98baa 100755
--- a/git-publish
+++ b/git-publish
@@ -485,6 +485,7 @@ def inspect_menu(tmpdir, to_list, cc_list, patches, suppress_cc, in_reply_to,
             print('\n'.join(output))
         elif a == 'a':
             break
+    return patches

 def parse_args():

@@ -760,8 +761,9 @@ branch.%s.pushRemote is set appropriately?  (Override with --no-url-check)''' %
                     cc = cc.union(output.splitlines())
             cc.difference_update(to)
             if inspect_emails:
-                inspect_menu(tmpdir, to, cc, patches, suppress_cc,
-                             options.in_reply_to, topic, options.override_cc)
+                selected_patches = inspect_menu(tmpdir, to, cc, patches, suppress_cc,
+                                                options.in_reply_to, topic,
+                                                options.override_cc)

             invoke_hook('pre-publish-send-email', tmpdir)

@@ -776,7 +778,7 @@ branch.%s.pushRemote is set appropriately?  (Override with --no-url-check)''' %
                     print('Deleted files: %s' % ' '.join(deleted))
                 return 1

-            git_send_email(to, cc, patches, suppress_cc, options.in_reply_to)
+            git_send_email(to, cc, selected_patches, suppress_cc, options.in_reply_to)
         except (GitError, GitSendEmailError, GitHookError, InspectEmailsError):
             return 1
         finally:
```

**Comment by Fabian-Gruenbichler** [comment]
On Wed, Feb 28, 2018 at 05:55:22PM -0800, Fam Zheng wrote:
> I've sent the patch to Stefan offline:
> ```
> From: Fam Zheng <famz@redhat.com>
> Date: Thu, 1 Mar 2018 09:51:07 +0800
> Subject: [PATCH] Fix 's' command
> 
> The modification to "patches" in inspect_menu is not propagated back to
> the final git_send_email command. Add a return value to fix that.
> 
> Signed-off-by: Fam Zheng <famz@redhat.com>
> 
> diff --git a/git-publish b/git-publish
> index ab9f6bf..4f98baa 100755
> --- a/git-publish
> +++ b/git-publish
> @@ -485,6 +485,7 @@ def inspect_menu(tmpdir, to_list, cc_list, patches, suppress_cc, in_reply_to,
>              print('\n'.join(output))
>          elif a == 'a':
>              break
> +    return patches
> 
>  def parse_args():
> 
> @@ -760,8 +761,9 @@ branch.%s.pushRemote is set appropriately?  (Override with --no-url-check)''' %
>                      cc = cc.union(output.splitlines())
>              cc.difference_update(to)
>              if inspect_emails:
> -                inspect_menu(tmpdir, to, cc, patches, suppress_cc,
> -                             options.in_reply_to, topic, options.override_cc)
> +                selected_patches = inspect_menu(tmpdir, to, cc, patches, suppress_cc,
> +                                                options.in_reply_to, topic,
> +                                                options.override_cc)

selected_patches is assigned conditionally (inspect_emails) here

> 
>              invoke_hook('pre-publish-send-email', tmpdir)
> 
> @@ -776,7 +778,7 @@ branch.%s.pushRemote is set appropriately?  (Override with --no-url-check)''' %
>                      print('Deleted files: %s' % ' '.join(deleted))
>                  return 1
> 
> -            git_send_email(to, cc, patches, suppress_cc, options.in_reply_to)
> +            git_send_email(to, cc, selected_patches, suppress_cc, options.in_reply_to)

but used unconditionally here, which means the --no-inspect-emails use
case is now broken ;)

**Comment by famz** [comment]
On Wed, 02/28 23:45, Fabian-Gruenbichler wrote:
> On Wed, Feb 28, 2018 at 05:55:22PM -0800, Fam Zheng wrote:
> > I've sent the patch to Stefan offline:
> > ```
> > From: Fam Zheng <famz@redhat.com>
> > Date: Thu, 1 Mar 2018 09:51:07 +0800
> > Subject: [PATCH] Fix 's' command
> > 
> > The modification to "patches" in inspect_menu is not propagated back to
> > the final git_send_email command. Add a return value to fix that.
> > 
> > Signed-off-by: Fam Zheng <famz@redhat.com>
> > 
> > diff --git a/git-publish b/git-publish
> > index ab9f6bf..4f98baa 100755
> > --- a/git-publish
> > +++ b/git-publish
> > @@ -485,6 +485,7 @@ def inspect_menu(tmpdir, to_list, cc_list, patches, suppress_cc, in_reply_to,
> >              print('\n'.join(output))
> >          elif a == 'a':
> >              break
> > +    return patches
> > 
> >  def parse_args():
> > 
> > @@ -760,8 +761,9 @@ branch.%s.pushRemote is set appropriately?  (Override with --no-url-check)''' %
> >                      cc = cc.union(output.splitlines())
> >              cc.difference_update(to)
> >              if inspect_emails:
> > -                inspect_menu(tmpdir, to, cc, patches, suppress_cc,
> > -                             options.in_reply_to, topic, options.override_cc)
> > +                selected_patches = inspect_menu(tmpdir, to, cc, patches, suppress_cc,
> > +                                                options.in_reply_to, topic,
> > +                                                options.override_cc)
> 
> selected_patches is assigned conditionally (inspect_emails) here

You're right. Will fix. (I never use --no-inspect-emails so my brain does s/if
inspect_emails:/if True:/ without /me noticing. :)
> 
> > 
> >              invoke_hook('pre-publish-send-email', tmpdir)
> > 
> > @@ -776,7 +778,7 @@ branch.%s.pushRemote is set appropriately?  (Override with --no-url-check)''' %
> >                      print('Deleted files: %s' % ' '.join(deleted))
> >                  return 1
> > 
> > -            git_send_email(to, cc, patches, suppress_cc, options.in_reply_to)
> > +            git_send_email(to, cc, selected_patches, suppress_cc, options.in_reply_to)
> 
> but used unconditionally here, which means the --no-inspect-emails use
> case is now broken ;)

Fam

**Comment by stefanha** [comment]
Thanks, I have merged Fam's v2 patch.
