### ISSUE TITLE
No install instructoins on README

### ISSUE THREAD

**Issue by ehabkost** [stefanha/git-publish#50]
commit 46a519c12817e155eb940a51eb2d1a224014be99 removed the install instructions from the documentation. We need to document how to install git-publish somewhere.

**Comment by stefanha** [comment]
Good point.  The `git-publish --setup` step is still documented but the Fedora/EPEL/Debian packages aren't mentioned anymore.

I have introduced a separate GitHub project page (README.md) that gives an overview of git-publish and documents how to install it:
https://github.com/stefanha/git-publish

**Comment by ehabkost** [comment]
@stefanha Are there instructions to install manually from the git repository anywhere? The old `README.rst` file had a "Install manually" section.
