### ISSUE TITLE
Show patch series status comment into cover letter

### ISSUE THREAD

**Issue by stefanha** [stefanha/git-publish#70]
When the cover letter editor opens there is not much information on the name of the patch series, the revision number, the To/Cc lists, etc.  Add this information in comments (that will not be included when the emails are sent) to give the user cues about what is going on.

Suggested-by: David Gibson <david@gibson.dropbear.id.au>

**Comment by stefano-garzarella** [comment]
I just sent a PR #75 to try to implement this useful suggestion.

**Comment by stefanha** [comment]
Fixed in PR #75
