### ISSUE TITLE
Package pulled from Debian Testing

### ISSUE THREAD

**Issue by gwd** [stefanha/git-publish#79]
Don't know if you're in a position to chase this, but it looks like the package has been pulled from `debian-testing` because the Debian package hasn't been updated to depend on python 3:

https://tracker.debian.org/pkg/git-publish

**Comment by stefanha** [comment]
@philmd Do you want to move the Debian packaging scripts to use Python 3?

**Comment by philmd** [comment]
The Debian package has been ported to Python 3, updated to version 1.6 and [uploaded](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=936617#27
) by @jelmer:
```sh
# apt-cache show git-publish
Package: git-publish
Version: 1.6.0-1
Installed-Size: 56
Maintainer: Philippe Mathieu-Daudé <f4bug@amsat.org>
Architecture: all
Depends: git, python3:any
Description: git command to prepare and store patch revisions as git tags
Description-md5: a1358afc7de20b96226ca69659a52a91
Multi-Arch: foreign
Homepage: https://github.com/stefanha/git-publish/blob/master/README.rst
Section: vcs
Priority: optional
Filename: pool/main/g/git-publish/git-publish_1.6.0-1_all.deb
Size: 19652
MD5sum: 76ef90c61c3fbeb3480cc3b4a552aa43
SHA256: 6a8b15654da2821b48287110f0558b48a93979b642a2ef369259d24d32f30079
```
Testing is done on [Debian Salsa CI](https://salsa.debian.org/philmd-guest/git-publish/pipelines/105664).
Many thanks to @jelmer for the sponsorship :)
