### ISSUE TITLE
** SUBJECT HERE *** not always replaced

### ISSUE THREAD

**Issue by elmarco** [stefanha/git-publish#81]
** SUBJECT HERE *** is not correctly replaced when Subject: is wrapped on multiple lines

git format-patch HEAD~ --cover-letter --subject-prefix="a very long long long long long long long long long test"

Produces:

```
Subject: [a very long long long long long long long long long test 0/1] ***
 SUBJECT HERE ***
```

This will miss the naive `[s.replace('*** SUBJECT HERE ***', message[0]) for s in lines]` search&replace.

**Comment by stefanha** [comment]
I've posted a pull request to fix this.  Please let me know if it works:
https://github.com/stefanha/git-publish/pull/82
