### ISSUE TITLE
`--pull request` doesn't add a tag description unless `--cover-letter` is used

### ISSUE THREAD

**Issue by ehabkost** [stefanha/git-publish#9]
I don't know what's the intended behavior here, but this confuses me: git-publish will never ask me for the tag description or use the one I set using `git publish --edit`, or even adds a default one like "Pull request", unless I use the `--cover-letter` option.

```
[qemu/x86>]$ git show x86-staging
tag x86-staging
Tagger: Eduardo Habkost <ehabkost@redhat.com>
Date:   Mon Mar 9 17:31:37 2015 -0300

X86 queue

X86 patches queued in the last few weeks. Mostly code cleanup and changes on
code assigning APIC ID.

commit 9886e834f47adabdbfd54ab606788ce7326e6779
Author: Eduardo Habkost <ehabkost@redhat.com>
[...]
[qemu/x86>]$ git publish --profile default --pull-request -b origin/master --annotate

You need a passphrase to unlock the secret key for
user: "Eduardo Habkost <ehabkost@redhat.com>"
4096-bit RSA key, ID 984DC5A6, created 2014-10-15

Counting objects: 1, done.
Writing objects: 100% (1/1), 796 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To git@github.com:ehabkost/qemu.git
 + 1b4bb31...5e252d0 x86-pull-request -> x86-pull-request (forced update)
8 files to edit
```

Then vim opens with the following message, and an empty tag description:

```
From 9886e834f47adabdbfd54ab606788ce7326e6779 Mon Sep 17 00:00:00 2001
From: Eduardo Habkost <ehabkost@redhat.com>
Date: Mon, 9 Mar 2015 17:37:17 -0300
Subject: [PULL 0/7] X86 patches
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

The following changes since commit 277263e1b320d759a760ba6c5ea75ec268f929e5:

  Merge remote-tracking branch 'remotes/agraf/tags/signed-ppc-for-upstream' into staging (2015-03-09 14:04:14 +0000)

are available in the git repository at:

  https://github.com/ehabkost/qemu.git tags/x86-pull-request

for you to fetch changes up to 9886e834f47adabdbfd54ab606788ce7326e6779:

  target-i386: Require APIC ID to be explicitly set before CPU realize (2015-03-09 16:30:03 -0300)

----------------------------------------------------------------

----------------------------------------------------------------

[...]
```

Is this the intended behavior? I would never guess that the --cover-letter option affect tagging behavior of `--pull-request` and I had to read the source code to find out how it works.

**Comment by stefanha** [comment]
On Mon, Mar 9, 2015 at 8:46 PM, Eduardo Habkost
<notifications@github.com> wrote:
> git-publish will never ask me for the tag description or use the one I set using git publish --edit, or even adds a default one like "Pull request", unless I use the --cover-letter option.

Hi Eduardo,
The semantics of --pull-request can still be changed.  They come from
another script I used before git-publish --pull-request and are not
consistent.

For starters, we should probably do the following to remove the
--cover-letter requirement:
diff --git a/git-publish b/git-publish
index a283fb7..072422e 100755
--- a/git-publish
+++ b/git-publish
@@ -502,8 +502,6 @@ def main():
     profile_message_var = get_profile_var(options.profile_name, 'message')
     if options.message is not None:
         message = options.message
-    elif options.pull_request:
-        message = False
     elif git_get_tag_message(tag_name_staging(topic)):
         # If there is a staged tag message, we definitely want a cover letter
         message = True

The cover letter is generated differently for pull requests, it might
be necessary to unify that code with the non-pull-request version.

Do you want to try adjusting the code to make it behave the way you expect?

Stefan

**Comment by ehabkost** [comment]
> Do you want to try adjusting the code to make it behave the way you expect?

I would, but I am completely unsure about the best behavior here.

1. On which cases should git-publish ask the user to edit the tag description? On which cases it shouldn't?
2. What should be the default tag description, if a cover letter was already set using `--edit`?

**Comment by stefanha** [comment]
On Fri, Mar 13, 2015 at 4:44 PM, Eduardo Habkost
<notifications@github.com> wrote:
> On which cases should git-publish ask the user to edit the tag description? On which cases it shouldn't?

When a regular patch series is sent, the editor is started with a
cover letter if there is more than 1 patch.

In the case of a pull request, I think it always makes sense to start
the editor with a cover letter by default.  It can be overridden with
--no-cover-letter.

> What should be the default tag description, if a cover letter was already set using --edit?

If --edit was used then the tag should be used to populate the cover
letter.  This already happens today for regular patch series.

Stefan

**Comment by stefanha** [comment]
I finally got around to fixing this!  Pull requests now automatically open an editor for the cover letter message.
